#!/usr/bin/env bash
# returns a custom header on request

apt-get -y update
apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'

custom_header="server_name _;\n\tadd_header X-Served-By \$HOSTNAME;"
sudo sed -i "s|server_name _;|$custom_header|" /etc/nginx/sites-enabled/default
echo "Holberton School" |sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo service nginx start
